### ISSUE TITLE
Default scene orientation

### ISSUE THREAD

**Issue by kielnino** [meshcat-dev/meshcat#136]
Hi, thank you for this amazing and easy to use viewer.

In my projekt I would like to have a more classical orientation of the scene with the z-axis not pointing up and down but away from the camera.

Can we make the default orientation set [here ](https://github.com/rdeits/meshcat/blob/master/src/index.js#L492) maybe customizable?

If this is an option, I can maybe propose a PR by myself.

**Comment by RussTedrake** [comment]
You can accomplish this already; just set the camera property immediately.  For instance, we do it here:
https://github.com/RobotLocomotion/drake/blob/5a93364f958dbf137d1461fe5e07c9f97de0eb49/geometry/meshcat.html#L101

**Comment by Vinggui** [comment]
@kielnino Check how this [PR works](https://github.com/RobotLocomotion/drake/pull/19968) with the camera, does it help you?
