### ISSUE TITLE
Rendering back faces

### ISSUE THREAD

**Issue by markisus** [meshcat-dev/meshcat#146]
Looks like back faces are not being rendered by default. Is there an option to render them? I have a mesh that is not water-tight and when looking from behind, parts of it disappear.

**Comment by jwnimmer-tri** [comment]
The front/back/both is a property of the _material_ you're assigning to a mesh:
https://threejs.org/docs/#api/en/materials/Material.side

One way to do that is a separate geometry & material, with the material specifying a side; see e.g. meshcat/test/opacity.html.

With a `_meshfile_object` like a glTF mesh, the material sided-ness is part of the asset; see e.g. meshcat/test/opacity.html.
