### ISSUE TITLE
symlinks are causing issues on Windows

### ISSUE THREAD

**Issue by nhz2** [meshcat-dev/meshcat#162]
Hello,
Thank you for maintaining this viewer. I am using it to view and debug simulations.

There are two symlinks in the test directory, `test/main.js => ../dist/main.js` and `test/main.min.js => ../dist/main.min.js`
These are preventing me from running the examples in the test directory on Windows, because Windows by default cannot create symlinks. This is also a issue for people trying to install the julia package on Windows Ref: https://github.com/rdeits/MeshCat.jl/issues/249

Can the symlinks be deleted and the `<script src="main.min.js"></script>` be replaced with `<script src="../dist/main.min.js"></script>`
in the tests? I would be happy to make a PR.

**Comment by jwnimmer-tri** [comment]
That seems OK to me.  WDYT @SeanCurtis-TRI?

**Comment by nhz2** [comment]
Can there be a new release for this version?

**Comment by SeanCurtis-TRI** [comment]
Hmmm.... I'm not sure what it means to have a release for `meshcat`. The only tag we have is from August, 2021.

@nhz2 Did you have something particular in mind?

**Comment by nhz2** [comment]
The Julia package requires a URL to download a tarball with known sha256 hash, and it seems like releases are a way to make those. https://docs.github.com/en/repositories/working-with-files/using-files/downloading-source-code-archives#stability-of-source-code-archives

But since this is specific to Julia, the tarball of this repo could go on a release of MeshCat.jl as well.

**Comment by jwnimmer-tri** [comment]
Ah, for checksum stability you need not only a release, but a source attachment to the release.  See for example the most recent numpy release:

https://github.com/numpy/numpy/releases/tag/v1.26.3

The ` Source code (tar.gz)` does not have a stable checksum.  Only an attachment like `numpy-1.26.3.tar.gz` is invariant.

**Comment by jwnimmer-tri** [comment]
Tracking at => https://github.com/meshcat-dev/meshcat/issues/164 now.
